name: Simple Artifact Example

on: [push]

jobs:
  upload:
    runs-on: ubuntu-latest
    steps:
      - name: Create file
        run: |
          echo "Hello from the upload job!" > hello.txt

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: hello-artifact
          path: hello.txt

  download:
    runs-on: ubuntu-latest
    needs: upload
    steps:
      - name: Download artifact
        uses: actions/download-artifact@v4
        with:
          name: hello-artifact

      - name: Show file content
        run: cat hello.txt
