name: My Custom Action Workflow

on: workflow_dispatch

jobs:
  greet:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Run a custom script
        run: echo "Hello from my custom GitHub Action!"
