name: Show Default GitHub Variables

on:
  push:
    branches:
      - main  # or use any branch you want

jobs:
  show-env:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Show all environment variables
        run: env

      - name: Show selected GitHub Actions variables
        run: |
          echo "GITHUB_REPOSITORY: $GITHUB_REPOSITORY"
          echo "GITHUB_REF: $GITHUB_REF"
          echo "GITHUB_SHA: $GITHUB_SHA"
        
