# .github/workflows/manual-trigger.yml

name: Manual Env check

on:
  workflow_dispatch:
    inputs:
      target_env:
        description: 'Target environment (e.g., staging, prod)'
        required: true
        default: 'staging'
jobs:
  show-env:
    runs-on: ubuntu-latest
    steps:
      - name: Show all default environment variables
        run: env

